### PR TITLE
Fix #196 - Elapsed time for each iteration doesn't seem right

### LINKED ISSUE #196: Elapsed time for each iteration doesn't seem right
**Summary:** 

I've added time benchmark for each iteration, and each class that runs validation rules within each iteration, to the INFO level logging so we can keep track of performance on larger feeds.

However, the times don't seem right.  When monitoring the MBTA feed, this is what I'm seeing (formatted for brevity):

~~~
BackgroundTask - Processed VehicleTripDescriptorValidator in 0.0 seconds
BackgroundTask - Processed VehicleValidator in 0.1 seconds
BackgroundTask - Processed TimestampValidation in 0.22 seconds
BackgroundTask - Processed StopTimeSequenceValidator in 0.1 seconds
BackgroundTask - Processed CheckTripDescriptor in 0.3 seconds
BackgroundTask - Processed StopValidator in 0.5 seconds
BackgroundTask - Processed FrequencyTypeZero in 0.0 seconds
BackgroundTask - Processed FrequencyTypeOne in 0.0 seconds
BackgroundTask - Processed http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb in 0.580 seconds
~~~

If you add up each of the class benchmarks, it's 1.22 seconds.  However, it's saying the entire iteration (including all classes) took 0.580 seconds.  This can't be right, because the entire iteration also includes the overhead of parsing the protobuf into Java objects and some other housekeeping - so the sum of rule benchmark times should be less than or equal to the total iteration time.

We're using `System.nanoTime()` for start/end time comparison, which should yield accurate results.  This requires a bit more investigation - maybe rounding issues?

**Steps to reproduce:** 

Run the validator on:

* GTFS-rt - http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb
* GTFS - http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip

**Expected behavior:** 

The sum of benchmark times for all rules should be the same or less than the total time it took to process the feed.

**Observed behavior:** 

Sum of benchmark times is more than the total iteration time.

**Platform:** 

Windows 7 Enterprise w/ jdk1.8.0_73

### PR DESCRIPTION
**Pull request by Suryakandukoori**
**Summary:**

Used thread synchronization when logging the duration.

**Expected behavior:** 

The sum of benchmark times for all rules should be the same or less than the total time it took to process the feed.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `mvn test` to make sure you didn't break anything
- [X] Format the title like "Fix #issue - short description of fix and changes"
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java [hunk 1]
```diff
@@ -180,16 +180,16 @@ public void run() {
 
             for (GtfsRtFeedModel gtfsRtFeedModel : gtfsRtFeedModelList) {
                 GtfsRealtime.FeedMessage message = mGtfsRtFeedMap.get(gtfsRtFeedModel.getGtfsRtId());
-                if (header == null) {
-                    // Save one header to use in our combined feed below
-                    header = message.getHeader();
-                } else {
-                    if (message.getHeader() != null && message.getHeader().getTimestamp() > header.getTimestamp()) {
-                        // Use largest header timestamp with multiple feeds - see #239
+                if (message != null) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java]: @Suryakandukoori I don't think this section of the changes should be in this PR.  Looks like this might be a fix for https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/253?  Could you please remove this section of changes from this PR?

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java [hunk 2]
```diff
@@ -199,16 +199,15 @@ public void run() {
...
 
             GtfsRealtime.FeedMessage combinedFeed = feedMessageBuilder.build();
-
-            // Use the same current time for all rules for consistency
-            long currentTimeMillis = System.currentTimeMillis();
-
-            // Run validation rules
-            for (FeedEntityValidator rule : mValidationRules) {
-                validateEntity(currentTimeMillis, combinedFeed, previousFeedMessage, gtfsData, gtfsMetadata, feedIteration, rule);
+            synchronized(_log) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java]: So does the underlying problem here seem to be that the `org.slf4j.Logger` isn't thread-safe?

https://stackoverflow.com/a/18543651/937715 seems to say it is.

I'd like to avoid synchronizing the entire execution of the rules if possible, as we'll want this to run in parallel when possible (e.g., when processing archived files - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/68).  As proposed here, we'd wait for one GTFS-rt feed to completely finish rule validation before the next could start.  This could block in the order of seconds for really big feeds.

Do you think synchronizing the `GtfsUtils.logDuration()` would have the same effect as the proposed change here?

**Comment by Suryakandukoori** [comment]
@barbeau 
I made the changes requested.

**Comment by barbeau** [comment]
Thanks @Suryakandukoori!
