### PR TITLE
Fix #188 - Show past sessions when user visits home page

### LINKED ISSUE #188: Show past sessions when user visits home page
**Summary:** 

Currently the internal data model of the validator is largely based around a single user monitoring a feed.  We have an issue open for expanding this to full support for multiple clients at https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/101.

To move towards that goal, I'd like to support saving a basic anonymous user identifier to our database, and when the user returns to the initial login screen we can show them a summary of their previous sessions.

Here's a sample mockup of what this could look like:

image

Clicking on the Session ID would take the user to something that looks like the current monitoring view, but there would be no ticking clock - it would just show the saved stats for that session:

image

Similarly, when the user clicks on the iteration number in the log, they'd see the iteration details page:

image

To support this, we'd need the following:

* Generate an anonymous user identifier - When the user goes to the index page, we can check to see if we've previously generated an anonymous user identifier for this particular client (likely saved as a cookie).  If we have, send this user ID to the server and get back a list of sessions specific to this user (see below for data model).  If we haven't, the server will return a new unique user ID (UUID?) that will be saved in a cookie in the client.
* Change how we're saving the current session starting time - I believe our current data model only supports a single session starting timestamp for each feed via `GtfsRtFeedModel.startTime`.  I've pulled up two browser windows simultaneously for the same feed, and it appears that the session counting timer gets reset to 0 in the 1st window when starting to monitor in the 2nd window.  As part of the changes for this feature, I believe `GtfsRtFeedModel.startTime` would be removed in favor of a new start time field per each session (see below).
* Add a `SessionModel` table with the fields `sessionId`, `gtfsRfFeedModel`, `gtfsFeedModel`, `startTime`, `endTime`, `userId`.  When an existing user goes to the index page, the client (browser) will send the user ID to the server and the records in this table will be used to generate the "Previous Session" view.  Similarly to how we're handling Log IDs, the older session ID shown to the user will always be 1.  But, internally, each session record will have it's own unique ID.  When the user starts monitoring a feed, a new record gets written to this table.  Figuring out how to populate `endTime` might be a bit tricky - if the user clicks "Stop" then that will be the `endTime`.  If they don't, we could pull back all records until the beginning of the next session, with the most recent Log iteration timestamp becoming the `endTime`.

@mohangandhiGH This issue is behind https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/181 and https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/186 in terms of priority if you have time.

**Steps to reproduce:** 

Go to the index page at http://localhost:8080

**Expected behavior:** 

Give me a way to view past sessions

**Observed behavior:** 

There is no way to view past session data.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Fixes #188.

**Expected behavior:** 

Past sessions are shown in welcome page.

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
@barbeau I have added 2 extra persistent columns 'errorCount' and 'warningCount' to the `Session` table other than the columns specified in the issue #188.

**Comment by mohangandhiGH** [comment]
@barbeau `sessionEndTime` of a particular session is added to a `Session` table when user clicks on `stop` button in **monitoring.html** or **monitoring.html** tab is closed or the window is closed.

**Comment by barbeau** [comment]
Thanks, looks awesome!  I'll try to review today or tomorrow.

**Comment by mohangandhiGH** [comment]
I tried to explain the higher view of handling **Past Sessions** data. If there is anything that is not clear, please let me know.

**Workflow:**
*  When a user enters `welcome` page, we send an AJAX request to server with parameter `clientId`. 
Here is the client request.
```
clientId = readCookie();
// Get past session data for the user.
$.get(server + "/api/gtfs-rt-feed/" + clientId + "/pastSessions").done(function (data) {
    if (clientId == "") {
        createCookie(data["clientId"], 1000);
    } else {
        displayPastSessionData(data);
    }
    sessionStorage.setItem("clientId", readCookie());
});
```
`clientId` is the cookie stored in browser. The `userId` we store in  `Session` table actually is the `clientId`.

*  So, if server receives `clientId` value as empty, it respond by creating  a UUID for client. The client receives the UUID and stores it as cookie with name `clientId`.
*  If server receives non-empty `clinetId`, it responds with all the **Past Sessions** data. The client then displays the received **Past Sessions** data. 
Here is how the server responds to the above AJAX request in **GtfsRtFeed.java** file.
```
// Returns past session details for a particular clientId.
    @GET
    @Path("/{clientId : .*}/pastSessions")
    @Produces(MediaType.APPLICATION_JSON)
    public Response getSessionData(
            @PathParam("clientId") String clientId) {

        if (clientId.isEmpty()) {
            String uuid = UUID.randomUUID().toString();
            JsonObject json = new JsonObject();
            json.addProperty("clientId", uuid);
            return Response.ok(json.toString()).build();
        }

        List<SessionModel> sessionModelList;
        Session session = GTFSDB.initSessionBeginTrans();
        long timeDiff;
        int rowId = 0;

        sessionModelList = session.createQuery(" FROM SessionModel" +
                " WHERE userId = '" + clientId + "'").list();

        Iterator iterator = sessionModelList.listIterator();
        SessionModel eachSessionModel;
        DateFormat timeFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        while(iterator.hasNext()) {
            eachSessionModel = (SessionModel) iterator.next();

            eachSessionModel.setRowId(++rowId);

            eachSessionModel.setStartTimeFormat(timeFormat.format(eachSessionModel.getSessionStartTime()));
            eachSessionModel.setEndTimeFormat(timeFormat.format(eachSessionModel.getSessionEndTime()));

            timeDiff = eachSessionModel.getSessionEndTime() - eachSessionModel.getSessionStartTime();
            timeFormat.format(timeDiff);
            eachSessionModel.setTotalTime(getTotalTimeFormat(timeDiff));
        }

        GenericEntity<List<SessionModel>> pastSessionsList = new GenericEntity<List<SessionModel>>(sessionModelList) {
        };
        return Response.ok(pastSessionsList).build();
    }
```

*  Then when user starts monitoring the feeds, a new session is created for each feed with stored `clientId`. You can see the client request here in **monitoring.js** file.
```
for (var gtfsRtFeed in gtfsRtFeeds) {
    if (gtfsRtFeeds.hasOwnProperty(gtfsRtFeed)) {
        $.ajax({
            url: server + "/api/gtfs-rt-feed/" + gtfsRtFeeds[gtfsRtFeed]["feedId"] + "/" + clientId + "/" + serverUpdateInterval + "/monitor",
            type: 'PUT',
            success: function (data) {
.......
```
You can see how a session is created at server side in **GtfsRtFeed.java** file in **getID** method here.
```
@PUT
    @Path("/{id}/{clientId}/{updateInterval}/monitor")
    public Response getID(
            @PathParam("id") int id,
            @PathParam("clientId") String clientId,
            @PathParam("updateInterval") int updateInterval) {
        // Store the timestamp when we start monitoring feeds that can be used to query database
        currentTimestamp = System.currentTimeMillis();
        //Get RtFeedModel from id
        Session session = GTFSDB.initSessionBeginTrans();
        GtfsRtFeedModel gtfsRtFeed = (GtfsRtFeedModel) session.createQuery(" FROM GtfsRtFeedModel "
                + "WHERE rtFeedID = "+id).uniqueResult();

        // Save the session data of a client monitoring feeds.
        SessionModel sessionModel = new SessionModel();
        sessionModel.setUserId(clientId);
        sessionModel.setSessionStartTime(currentTimestamp);
        sessionModel.setGtfsRtFeedModel(gtfsRtFeed);

        session.save(sessionModel);
        GTFSDB.commitAndCloseSession(session);
........
```
*  Finally, a session is closed when a user clicks on `stop` button or monitoring tab is closed or window is closed.
Here is the client request in **monitoring.js** `stopMonitor` method.
```
........
for (var sessionId in sessionIds) {
        if (sessionIds.hasOwnProperty(sessionId)) {
            $.ajax({
                url: server + "/api/gtfs-rt-feed/" + sessionIds[sessionId] + "/closeSession",
                type: 'PUT'
            });
        }
    }
```
* Then the server updates the `Session` table in **GtfsRtFeed.java** file, **updateSessionData** method.
```
// Update sessionEndTime, errorCount and warningCount of a session.
    @PUT
    @Path("/{sessionId}/closeSession")
    public void updateSessionData(
            @PathParam("sessionId") int sessionId) {
............
```

**Comment by barbeau** [comment]
Thanks!  That will help me review.  Haven't gotten to this yet - I may be able to review tomorrow, if not it may be next Tues.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 1]
```diff
@@ -132,56 +131,79 @@ public Response getRtFeeds() {
     private static HashMap<String, ScheduledExecutorService> runningTasks = new HashMap<>();
 
     @PUT
-    @Path("/{id}/{updateInterval}/monitor")
-    public Response getID(@PathParam("id") int id, @PathParam("updateInterval") int updateInterval) {
+    @Path("/{id}/{clientId}/{updateInterval}/monitor")
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Could you make these query string URL parameters instead of path parameters? This really applies to all the API calls. A variable should really only be a path  parameter if we are performing an operation on a particular object, and the path references the ID. Github uses this structure to refer to specific issues and pull requests. Things like update intervals and start and end times should really be query parameters, because their order in the path is somewhat arbitrary - they don't fit neatly into a hierarchy.

Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Unless I'm missing something here - let me know if I am.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 2]
```diff
@@ -330,6 +354,84 @@ public Response getIterationDetails(
...
+        }
+
+        GenericEntity<List<SessionModel>> pastSessionsList = new GenericEntity<List<SessionModel>>(sessionModelList) {
+        };
+        return Response.ok(pastSessionsList).build();
+    }
+
+    // Update sessionEndTime, errorCount and warningCount of a session.
+    @PUT
+    @Path("/{sessionId}/closeSession")
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: I think session ID is fine as a path parameter here because we are performing an operation on that particular session.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 3]
```diff
@@ -330,6 +354,84 @@ public Response getIterationDetails(
         return Response.ok(gtfsRtFeedIterationModel).build();
     }
 
+    // Returns past session details for a particular clientId.
+    @GET
+    @Path("/{clientId : .*}/pastSessions")
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: IMHO client ID would be better as a query parameter here because you aren't performing an operation on that client - you're asking to retrieve information about a particular client (I.E., a query).  But let me know if I'm missing something.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 4]
```diff
@@ -132,56 +131,79 @@ public Response getRtFeeds() {
...
+            "/{startTime}/{endTime}")
     @Produces(MediaType.APPLICATION_JSON)
     public Response getMonitorData(
             @PathParam("id") int gtfsRtId,
             @PathParam("summaryCurPage") int summaryCurPage,
             @PathParam("summaryRowsPerPage") int summaryRowsPerPage,
             @PathParam("toggledData") String hideErrors,
             @PathParam("logCurPage") int logCurPage,
-            @PathParam("logRowsPerPage") int logRowsPerPage) {
+            @PathParam("logRowsPerPage") int logRowsPerPage,
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Seems like ID should be a path parameter here and everything else a query parameter.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java (hunk 1 above)
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Given that this is an HTTP Put and modifies the database and starts an action  (monitoring), this should probably be named "startMonitor" instead of "getID".

**Comment by barbeau** [comment]
Just added some quick comments from browsing through code. I'll see if I can go through your work flow comment and actually run the code tomorrow.

**Comment by barbeau** [comment]
Also, if you have questions for which API parameters should be part of path and which should be query parameters, feel free to just comment here with proposals for the API and we can discuss before you write the code.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/SessionModel.java [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+    @JoinColumn(name = "rtFeedId")
+    private GtfsRtFeedModel gtfsRtFeedModel;
+
+    @Column(name = "startTime")
+    private long sessionStartTime;
+
+    @Column(name = "endTime")
+    private long sessionEndTime;
+
+    @Column(name = "userId")
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/SessionModel.java]: Let's call this the same thing across both the server and Javascript code - right now it's `userId` server-side, and `clientId` in Javascript.  I think `clientId` is a more accurate name, so let's use that server-side as well.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 6]
```diff
@@ -330,6 +354,84 @@ public Response getIterationDetails(
...
+        return Response.ok(pastSessionsList).build();
+    }
+
+    // Update sessionEndTime, errorCount and warningCount of a session.
+    @PUT
+    @Path("/{sessionId}/closeSession")
+    public void updateSessionData(
+            @PathParam("sessionId") int sessionId) {
+
+        SessionModel sessionModel = new SessionModel();
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: I believe you don't actually need to instantiate a new `SessionModel` here - it can just be `SessionModel sessionModel;`, or just declare it as part of line 410 `SessionModel sessionModel = (SessionModel) session....`.

**Comment by barbeau** [comment]
First, it's awesome to be able to see past session data :).

I just ran it with a few feeds, using this process:

1. Go to localhost, add HART TripUpdates feed, start monitoring feed, click on "Stop", close tab
1. While the server is still running (and the BackgroundTask is still running), open a new tab and go to localhost again, add MBTA feed, start monitoring feed, and click on "Stop"
1. While server is still running, add HART VehicleUpdates feed, start monitoring

It seems like it started mixing results, where it was giving me a `E028	Vehicle position outside agency coverage area` error for the MBTA feed using a vehicle position from HART's data.  If I went to the Iteration Details page the error showed up there with a vehicle_id that wasn't in the MBTA GTFS-rt plain text version of the protobuf in the left column.

I'm not sure if the above is a result of the changes in this PR, or if it's part of the larger problem of not supporting multiple client (https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/101).  I would have expected the above to work and still properly isolate sessions, though, and not mix data from two different feeds/agencies from the same browser, though.

@mohangandhiGH Could you please take a look and see if the above behavior is a result of the code in this PR, or a previously existing problem?

**Comment by barbeau** [comment]
@mohangandhiGH I just tested the mixing data issue, and I'm able to reproduce it (with `E011 GTFS-rt stop_id does not exist in GTFS data`) in the current `master` branch - so it's a separate issue from this PR.  Don't worry about it for this PR, I'll open a separate issue for it.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 7]
```diff
@@ -330,6 +354,84 @@ public Response getIterationDetails(
...
+        sessionModelList = session.createQuery(" FROM SessionModel" +
+                " WHERE userId = '" + clientId + "'").list();
+
+        Iterator iterator = sessionModelList.listIterator();
+        SessionModel eachSessionModel;
+        DateFormat timeFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
+        while(iterator.hasNext()) {
+            eachSessionModel = (SessionModel) iterator.next();
+
+            eachSessionModel.setRowId(++rowId);
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Could you please split this into two separate statements - `eachSessionModel.setRowId(rowId);` here, and `rowId++` after it?  As a style I prefer not to use `++` before the variable use.

**Comment by mohangandhiGH** [comment]
@barbeau Thanks Sean for the review.
Yah, I will leave mixing data issue as is and I will definitely try to address the URL path vs. query parameters and other code changes you reviewed. I will let you know if I have any issues addressing URL path vs. query parameters.

**Comment by mohangandhiGH** [comment]
@barbeau Please review the latest changes.

**Comment by barbeau** [comment]
Thanks @mohangandhiGH!  I'll hopefully give this another test soon.

So can we eliminate `GtfsRtFeedModel.startTime`, or is that field still being used?

**Comment by mohangandhiGH** [comment]
@barbeau I think we are only setting `GtfsRtFeedModel.startTime`field and not using anywhere. 
We can eliminate this filed if not needed.

**Comment by barbeau** [comment]
@mohangandhiGH Thanks, looks great!
