### PR TITLE
Fix #62 - Can't load GTFS data from a URL

### LINKED ISSUE #62: Can't load GTFS data from an URL
When running the application, it won't load GTFS data from the provided URL.

### Steps to reproduce:

1. Clone `master` branch
1. Run the application
1. Enter a GTFS URL to the GTFS zip file

Reported by @scrudden.  @scrudden let me know if I got any of the above incorrect.

@mohangandhiGH Could you please take a look at this?

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Modified to correctly read the file name from given static Gtfs URL.

But, you will see an issue https://github.com/conveyal/gtfs-validator/issues/28, if your static Gtfs file does not have the optional file `calendar_dates.txt`. The conveyal code is missing to check null values for it. You can see the description about the issue mentioned in the above URL. The fix for the issue is created in PR https://github.com/conveyal/gtfs-validator/pull/29. 
Once the PR in conveyal project is fixed, you can expect the application to work as mentioned in the below **Expected behavior** section.

**Expected behavior:** 

*  Try to run the application if you installed locally using, http://localhost:8080
*  Use different static Gtfs data links. For example, you may use below provided links to test.
https://drive.google.com/uc?export=download&id=0BzTMCDngWQJ4eElfWV9tZE1vRUU
https://dl.dropboxusercontent.com/u/107527881/final_dt2.zip
http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip
http://gohart.org/google/google_transit.zip
*  For all these feed links provided, the application should download these files successfully and start running.

### CODE REVIEW

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java [hunk 1]
```diff
@@ -123,7 +123,10 @@ public Response postGtfsFeed(@FormParam("gtfsurl") String gtfsFeedUrl) throws Js
                             + "WHERE gtfsUrl = '"+gtfsFeedUrl+"'").uniqueResult();
         GTFSDB.commitAndCloseSession(session);
         ObjectMapper mapper = new ObjectMapper();
-        downloadGtfsFeed(saveFilePath, connection);
+        Response.Status response = downloadGtfsFeed(saveFilePath, connection);
+        if(response == null)
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: Please use braces for all If statements, even if they are one line:
`if (response == null) {`

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java [hunk 2]
```diff
@@ -221,8 +224,9 @@ private String getSaveFilePath(String gtfsFeedUrl, HttpURLConnection connection)
         } else {
             //Extracts file name from header field
             int index = disposition.indexOf("filename=");
+            int filenameLastIndex = disposition.indexOf("\"", index+10);
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: I believe this will fail on Linux and Mac due to hard coded Windows path character \. Could you please see if you can make this platform independent?

**Comment by barbeau** [comment]
Thanks Mohan! A few comments inline.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java (hunk 2 above)
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: If you could add a unit test for loading GTFS data as well that would be great. Travis is Linux based so the test would fail on Travis if the code isn't platform independent.

Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: Here, I was using \  to escape double quote " character. I believe escaping a character is platform independent.

Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: Ah, right. You're correct.  So this is Ok as is, although it would still be nice to have unit tests for loading GTFS.   If this is straight forward to implement please add it, if not we can live without it for now.

Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: Sure, I will try to add the unit tests.
