### PR TITLE
Fix #266 - Add more time duration logging in BackgroundTask

### LINKED ISSUE #266: Add time duration logging for protocol buffer fetch and decode stages
**Summary:** 

Currently, we log the amount of time each rule takes to execute on a feed, as well as the duration of the entire time it took to process a given feed iteration.

However, the duration of two parts of the iteration, protocol buffer fetch and decoding, are not currently measured.  Typically these are very quick, but when they are not it causes problems with looking at the log, as the total time for an iteration isn't the sum of the rule processing times.

We should add time duration logging for the protocol buffer fetch and decode stage, and separately if possible.

**Steps to reproduce:** 

Run the tool on a feed

**Expected behavior:** 

Tell me how long it took to fetch and decode the protocol buffer message for each iteration

**Observed behavior:** 

Fetch and decode stage durations aren't logged.

### PR DESCRIPTION
**Pull request by barbeau**
* Added for HTTP request and processing, protobuf decoding, and database writes for each rule
* Also add break in between iterations to make it easier to read

**Expected behavior:** 

Provide more granular logging in `BackgroundTask`, such as:

~~~
---------------------
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
https://gtfsrt.api.translink.com.au/Feed/SEQ gtfsRtFeedUrl.openStream() in 0.331 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ IOUtils.toByteArray(in) in 2.028 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ protobuf decode in 0.011 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
CrossFeedDescriptorValidator - rule = 0.0 seconds, database = 0.0 seconds
VehicleValidator - rule = 0.047 seconds, database = 0.001 seconds
TimestampValidator - rule = 0.03 seconds, database = 0.031 seconds
StopTimeUpdateValidator - rule = 0.033 seconds, database = 0.019 seconds
TripDescriptorValidator - rule = 0.013 seconds, database = 0.08 seconds
StopValidator - rule = 0.013 seconds, database = 0.001 seconds
FrequencyTypeZeroValidator - rule = 0.0 seconds, database = 0.0 seconds
FrequencyTypeOneValidator - rule = 0.0 seconds, database = 0.0 seconds
HeaderValidator - rule = 0.0 seconds, database = 0.0 seconds
Processed https://gtfsrt.api.translink.com.au/Feed/SEQ in 2.697 seconds
~~~

### CODE REVIEW

**Comment by barbeau** [comment]
@Suryakandukoori Can you please take a look?

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java [hunk 1]
```diff
@@ -86,7 +86,8 @@ public void run() {
             GtfsMetadata gtfsMetadata;
             // Holds data needed in the database under each iteration
             GtfsRtFeedIterationModel feedIteration;
-            StringBuffer consoleOutput;
+            StringBuffer consoleOutput = new StringBuffer();
+            ;
```
Comment (Suryakandukoori) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java]: unrequired semicolon

Comment (barbeau) [reply src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java]: Whoops! Not sure how that got there. Thanks, I'll fix it.
