### PR TITLE
Fix#98 - Show users detailed error messages in the UI

### LINKED ISSUE #98: Show users detailed error messages in the UI
**Summary:** 

Currently, we're relying heavily on logging to inform users what is happening when something goes wrong.  We should show fatal errors messages in the UI to better explain what is happening.

This is especially important in the context of using HTTPS for GTFS and GTFS-rt URLs, as hosting feeds securely will become more and more common, and the user may need to install the [JCE Extension](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) in order for HTTPS URLs to work on their machine as detailed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/89.

We can test showing a detailed HTTPS failure message in the UI using https://mta.maryland.gov/_googletransit/latest/google_transit.zip and http://gtfsrt.mta.maryland.gov:8888/TMGTFSRealTimeWebService/TripUpdate/TripUpdates.pb.

**Steps to reproduce:** 

1. Use invalid URLs for feeds like http://api.tampa.onebusaway.org:8088/trip-updates2 and http://gohart.org/google/google_transit2.zip

or

1. Use HTTPS URLs like https://mta.maryland.gov/_googletransit/latest/google_transit.zip  (and the companion GTFS-rt URL that isn't HTTPS is http://gtfsrt.mta.maryland.gov:8888/TMGTFSRealTimeWebService/TripUpdate/TripUpdates.pb) **without** installing the JCE Extension.

...and any other error cases (invalid zip, etc.).

**Expected behavior:** 

Tell the user what went wrong

In the first case, let them know it's an invalid URL.

In the second case, tell them they need to install the JCE Extension.

**Observed behavior:** 

We show the user a red bar without any error message:

image

**Platform:** 

Windows 7 Enterprise SP1 with JDK 1.8.0_73 64bit

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Here are some screenshots of error messages for invalid requests. 
*  Provide an invalid static gtfs URL [http://gohart.org/google/google_transit2.zip](http://gohart.org/google/google_transit2.zip) and valid GTFS-RT feed [ http://api.tampa.onebusaway.org:8088/trip-updates]( http://api.tampa.onebusaway.org:8088/trip-updates). It displays the error as

image

*  Provide a valid static gtfs URL [http://gohart.org/google/google_transit.zip](http://gohart.org/google/google_transit.zip) and valid GTFS-RT feed [ http://api.tampa.onebusaway.org:8088/trip-upda]( http://api.tampa.onebusaway.org:8088/trip-upda). It displays the error as

image

Fixes #98. 

**Expected behavior:** 

The application is expected to show detailed error mesage in UI.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java [hunk 1]
```diff
@@ -127,8 +129,11 @@ public Response postGtfsFeed(@FormParam("gtfsurl") String gtfsFeedUrl) {
         GtfsFeedModel gtfsFeed = (GtfsFeedModel) session.createQuery("FROM GtfsFeedModel "
                             + "WHERE gtfsUrl = '"+gtfsFeedUrl+"'").uniqueResult();
         Response.Status response = downloadGtfsFeed(saveFilePath, connection);
-        if(response == null) {
-            return generateError("Download Failed", "Downloading static GTFS feed from provided Url failed", Response.Status.BAD_REQUEST);
+        if (response == Response.Status.BAD_REQUEST) {
+            return generateError("Download Failed", "Downloading static GTFS feed from provided Url failed.", Response.Status.BAD_REQUEST);
+        }
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java]: Minor formatting issue - can you please move the `else if...` to the same line as the preceding bracket?

So it would be:

`} else if (response == Response.Status.FORBIDDEN) {`

Same for other occurrences in this PR.

File: src/main/resources/webroot/custom-js/loading.js [hunk 2]
```diff
@@ -145,18 +147,21 @@ function downloadGTFSFeed() {
...
+        errorMessage["title"] = "Invalid URL";
+        errorMessage["errorDescription"] = "No GTFS URL Given";
+        feedErrorDisplay(errorMessage);
 
-    } else if (paramVal === "") {
-        //No URL for the given feed entered. Show status
-        feedErrorDisplay("No GTFS URL Given");
-    } else {
+    }
+    else {
```
Comment (barbeau) [inline src/main/resources/webroot/custom-js/loading.js]: Same formatting isssue - pleaes change to `} else {`

**Comment by barbeau** [comment]
Looks good, thanks!
