### PR TITLE
Fix #96 - Only log validation warnings/errors for unique responses

### LINKED ISSUE #96: Only log validation warnings/errors for unique responses
**Summary:** 

Currently, every time we poll the GTFS-rt feed we do the following in `BackgroundTask`:

1. Retrieve the GTFS-rt PB feed message
1. Hash it and compare it to the hash of the most recent GTFS-rt pb message in our local database for this feed URL
1. If the feeds are different, we set a boolean variable indicating that the new feed is unique (i.e., its the first time we've seen that instance of the feed)
1. Store the new feed message in our database
1. Run the new feed message through rule validation and log errors/warnings to database

We should change this so we only log rule validation warnings/errors on unique feeds.  Otherwise we're simply logging duplicate errors/warnings.

So, the process should change to:

1. Retrieve the GTFS-rt PB feed message
1. Hash it and compare it to the hash of the most recent GTFS-rt pb message in our local database for this feed URL
1. If the feeds are different, we set a boolean variable indicating that the new feed is unique (i.e., its the first time we've seen that instance of the feed)
1. Store the new feed message in our database
1. If the feed is unique (i.e., first time we've seen this exact message), run the new feed message through rule validation and log errors/warnings to database

(Note that https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/92 also changes the above process slightly to avoid storing duplicate PB messages in the database)

**Steps to reproduce:** 

1. Start the validator and enter GTFS and GTFS-rt feed

**Expected behavior:** 

Only log errors/warnings to database for the first time a new feed message is observed

**Observed behavior:** 

Errors/warnings are duplicated - the validation is run on every message returned by an HTTP request, instead of just the first instance of that message.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Log validation warnings/errors for unique responses. Fixes #96. 

**Expected behavior:** 

Only unique response PB feeds are validated and warnings/errors are stored in database for those unique feeds.
 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java [hunk 1]
```diff
@@ -121,6 +121,10 @@ public void run() {
                 }
                 session.save(feedIteration);
                 GTFSDB.commitAndCloseSession(session);
+
+                if(!isUniqueFeed) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java]: Minor formatting issue - can you please reformat as `if (!isUniqueFeed) {`?

It's missing a space after `if`.

**Comment by barbeau** [comment]
Looks good, thanks!
