### PR TITLE
Fix #286 - Disable shapes

### LINKED ISSUE #286: Add website option to disable shapes.txt-based metadata
**Summary:** 

This issue is the website version of https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/284, which added this option to the command-line process.

Basically, we want a checkbox in the website UI that would allow someone to turn off the processing of GTFS shapes.txt to avoid out of memory errors.

Here's a potential UI mockup:

image

2nd box would default to true (checked).

If the 2nd box is unchecked, we would pass `true` into the `GtfsMetadata` contructor within `BackgroundTask`:

~~~
ignoreShapes = true;
gtfsMetadata = mGtfsMetadata.computeIfAbsent(mCurrentGtfsRtFeed.getGtfsFeedModel().getFeedId(),
		k -> new GtfsMetadata(mCurrentGtfsRtFeed.getGtfsFeedModel().getGtfsUrl(),
				TimeZone.getTimeZone(mCurrentGtfsRtFeed.getGtfsFeedModel().getAgency()),
				gtfsData, ignoreShapes));
~~~

**Steps to reproduce:** 

Run the tool and try to validate the Netherlands feed:
* GTFS - http://gtfs.openov.nl/gtfs/gtfs-openov-nl.zip (~261MB)
* TripUpdates - http://gtfs.openov.nl/gtfs-rt/tripUpdates.pb (~8.4MB)

**Expected behavior:** 

Give me an option to turn off GTFS shapes.txt processing for huge feeds that cause OutOfMemoryErrors

**Observed behavior:** 

The website will take forever to process the feed, then eventually fail with an error.

**Platform:** 

It's been a while since I repro'd this from the website - see #284 for the details on repro via batch validator

### PR DESCRIPTION
**Pull request by Suryakandukoori**
**Summary:**

Added checkbox and relevant code to enable/disable validation of shapes.txt.

**Expected behavior:** 

Checkbox, if checked, enables validation of shapes.txt, unchecked disables the validation.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `mvn test` to make sure you didn't break anything
- [X] Format the title like "Fix #issue - short description of fix and changes"
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 1]
```diff
@@ -134,7 +134,8 @@ public Response getRtFeeds() {
     public Response startMonitor(
             @PathParam("id") int id,
             @QueryParam("clientId") String clientId,
-            @DefaultValue("10") @QueryParam("updateInterval") int updateInterval) {
+            @DefaultValue("10") @QueryParam("updateInterval") int updateInterval,
+            @QueryParam("enableShapes") String enableShapesStr) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: The `enableShapesStr` parameter should have a default value of `true`.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 2]
```diff
@@ -156,8 +157,12 @@ public Response startMonitor(
                 leastInterval< runningTasks.get(sessionModel.getGtfsRtFeedModel().getGtfsRtUrl()).getUpdateInterval()){
             intervalUpdated=true;
         }
+        boolean enableShapes = true;
+        if ("unchecked".equals(enableShapesStr)) {
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Instead of `unchecked`, let's use the value `true`.  I'd like to think ahead to this API being used outside of just our web UI, in which case there may not be a checkbox associated with this value, it may just be set programmatically in code.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java (hunk 1 above)
Comment (Suryakandukoori) [reply src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: @barbeau the default value of 'true' is set in index.js. Do you think its necessary even at this location?

Comment (barbeau) [reply src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Yes, I think it's necessary here - let's assume that UIs/clients other than our `index.js` might use this API.  So, I'd like this to work without considering what exists in `index.js`.

**Comment by Suryakandukoori** [comment]
@barbeau I made the requested changes
