### PR TITLE
Fix #120 and #133 - Displaying Feed iteration numbers in sequential order

### LINKED ISSUE #120: Feed iteration numbers are incorrect
**Summary:** 

The iteration numbers shown in the "Log" are incorrect.  They currently represent the total number of HTTP requests, not unique responses.

For example, in the below screenshot there have been 4 total HTTP requests, but only 2 unique responses.  The Iteration column shows two records:

* 4
* 1

They should be:

* 2
* 1

image

**Steps to reproduce:** 

Load any feed and start monitoring it

**Expected behavior:** 

Iteration numbers should only increment on unique responses, not total HTTP requests.  I'd expect the Iteration numbers in above screenshot to be:

* 2
* 1

**Observed behavior:** 

Iteration numbers are being determined by total HTTP requests.  Iteration numbers in above screenshot are:

* 4
* 1

**Platform:** 

Windows 7 Enterprise with jdk1.8.0_73

### LINKED ISSUE #133: Iteration timestamp doesn't match GTFS-rt header timestamp
**Summary:** 

Looking at the details of a GTFS-rt feed, I'm noticing that the "Timestamp" value in log records doesn't match the GTFS-rt header timestamp.

For example, see:

image

The Iteration timestamp is `1492186570`, while the GTFS-rt header timestamp is `1492186565`.

I think the more useful value to show in the Summary/Log UI is the timestamp of the GTFS-rt header, because that's what producers/consumers will use to reference the actual data.  But, I can see the internal GTFS-rt validation server current time timestamp being important if we were to generate graphs and other data for when requests were made, etc.

Let's store both timestamps in the database and just show the GTFS-rt header timestamp in the Summary/Log UI.  Let's also add a little "tooltip" so when you hover over the field name it says "GTFS-rt header timestamp", to make it clearer what we're showing in the log.

See https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp for tooltip example.

**Steps to reproduce:** 

1. Start monitoring a feed
1. Click on the "Iteration" number for any record in the log

**Expected behavior:** 

The Iteration timestamp should match the GTFS-rt header timestamp

**Observed behavior:** 

Timestamps are different

**Platform:** 

Windows 7 Enterprise with jdk1.8.0_73

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Fixes #120 and Fixes #133.

**Expected behavior:** 

Now the Feed iterations appear in sequential order in Log table. 
Everything in monitoring page is now displayed starting from the time when the monitoring of feeds are started.
Screenshot:

image
image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
I liked writing the queries.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/TimeStampHelper.java [hunk 1]
```diff
@@ -18,9 +18,10 @@
 package edu.usf.cutr.gtfsrtvalidator.helper;
 
 import java.util.Date;
+import java.util.concurrent.TimeUnit;
 
 public class TimeStampHelper {
     public static long getCurrentTimestamp() {
-        return (long) Math.ceil((double) new Date().getTime() / 1000);
+        return TimeUnit.MILLISECONDS.toSeconds(new Date().getTime());
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/TimeStampHelper.java]: Nice job using `TimeUnit.MILLISECONDS.toSeconds()`!  We should really use millisecond precision for timestamps and use `System.currentTimeMillis()` instead of instantiating a new Date object, but let's handle that as part of #133.  I just commented on this at https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/133#issuecomment-294488136.

**Comment by barbeau** [comment]
>I liked writing the queries.

Wow, yeah, those are crazy complex.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/TimeStampHelper.java (hunk 1 above)
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/TimeStampHelper.java]: Actually, looks like we might need to address the precision issue in this PR after all.  I'll comment shortly in my review.

**Comment by mohangandhiGH** [comment]
@barbeau Force pushed the changes requested.
>> As you say, the queries here are really complex. Could you please write some unit tests to verify behavior? For example, insert some dummy records, and then verify that the query returns what you would expect. Otherwise no one will ever want to change this code :).

I have written unit tests for `ViewErrorSummaryModel` and `ViewErrorLogModel` views.

>>Related to the above - is it possible to separate some of the sub-queries into Views, or something similar, to reduce some of the nested JOINs? If this was a SQL database that's what I would do, but I'm not sure how this is typically handled via Hibernate.

As the queries written in classes `ViewErrorSummaryModel` and `ViewErrorLogModel` are already views, I didn't find any way to use views in an other view. 

>>There seem to be some synchronization issues, which might be caused by the fact that we're storing all timestamps in second precision. The synch issues I'm seeing are the HTTP request and unique response counts being 0, but records still showing up in the table.
I also saw the reverse, where the count was one but, using the Tampa feed that should have generated the missing timestamp error on every iteration, no records showed up in the log.
So, let's change to storing all timestamps (including GTFS-rt timestamps) in millisecond precision. If we're calculating our own times it should be using System.currentTimeMillis() to avoid instantiating a Date object. 

Updated to use System.currentMillis for column  iterationTimestamp.

**Comment by barbeau** [comment]
Thanks! Did the timestamp conversion to milliseconds seem to resolve the synch issues?

**Comment by mohangandhiGH** [comment]
Yes Sean, I didn't find any synchronization issues while I'm running the application at my side.

**Comment by mohangandhiGH** [comment]
@barbeau In the new commit, updated `testSQLScript.sql` records  to use negative values so that there is no need to clean the database. Now, we are storing negative values for primary keys to test Log and Summary table queries.

When we run the application on feeds, every primary key value starts from 1 however.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java [hunk 2]
```diff
@@ -93,7 +93,7 @@
             "Arrival predictions for each trip in the feed must match the sequential order for the trips in the block. For example, if we have trip_ids 1, 2, and 3 that all belong to the same block, and the vehicle trips trip 1, then trip 2, and then trip 3, the arrival predictions should increase chronologically for trips 1, 2, and 3. For example, trip 3 predictions shouldn't be earlier in the feed than trip 2 predictions.",
             "predictions are not ordered by appearance in block");
 
-    public static final ValidationRule E015 = new ValidationRule("E014", "ERROR", "All stop_ids referenced in GTFS-rt feeds must have the location_type = 0",
+    public static final ValidationRule E015 = new ValidationRule("E015", "ERROR", "All stop_ids referenced in GTFS-rt feeds must have the location_type = 0",
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java]: Thanks for catching this!  I missed changing this in https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/4444259605742d9527d3e89ff9c454bafd6c45e9 for #146.

**Comment by mohangandhiGH** [comment]
@barbeau As we discussed in Friday's meeting, updated changes to use single request to server to update  monitor data.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java [hunk 3]
```diff
@@ -141,91 +144,95 @@ public Response getID(@PathParam("id") int id, @PathParam("updateInterval") int
...
-    @GET
-    @Path("/{id : \\d+}/feedIterations")
-    @Produces(MediaType.APPLICATION_JSON)
-    public Response getFeedIterationsCount(@PathParam("id") int id) {
-        ViewFeedIterationsCount iterationsCount;
-        Session session = GTFSDB.InitSessionBeginTrans();
-        iterationsCount = (ViewFeedIterationsCount) session.createNamedQuery("feedIterationsCount", ViewFeedIterationsCount.class)
-                            .setParameter(0, id).uniqueResult();
-        GTFSDB.commitAndCloseSession(session);
+        GTFSDB.closeSession(session);
```
Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: I assume the reason you switched from ` GTFSDB.commitAndCloseSession(session);` to just `GTFSDB.closeSession(session);` is because this is a READ operation that doesn't write any data to the server?  Were there performance issues you saw when committing the session?  Or was there another reason why you used a new method that doesn't include a commit?

Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: When I do `GTFSDB.commitAndCloseSession(session)' on single READ-ONLY queries in a session, I didn't see any issues with committing the transaction. But when I did it for multiple READ_ONLY queries it is actually throwing an exception `Batch update returned unexpected row count from update: 0 actual row count: 0 expected: 1`.

**Comment by mohangandhiGH** [comment]
>>I think there is one remaining item to resolve before merge - when clicking on the "Iteration" number to view the plain text version of the feed, I'm still seeing the Iteration number in the popup window title that doesn't start at one

@barbeau Oh yes, I missed variable update in monitoring.html file. I directly committed that change from Github.

File: src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java (hunk 3 above)
Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: So, I'm just closing the session without committing the transaction for multiple READ queries.

Comment (barbeau) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Ok, thanks. Can you just add a Javadoc comment to the GTFSDB.closeSession() method saying that it should be used for multiple READ queries in the same session?

Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Yes Sean, I will do that.

Comment (mohangandhiGH) [inline src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java]: Added Javadoc comment Sean.

**Comment by barbeau** [comment]
Thanks @mohangandhiGH!

Something still appears off with the Iteration numbers though.  Sometimes when I click on them in the Log, nothing happens (it should open the popup window with the plain text version of the feed), and I see this in the server log:

~~~
[qtp7548983-21] WARN org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsRtFeed.getFeedMessage(GtfsRtFeed.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	... 17 more
[qtp7548983-21] WARN org.eclipse.jetty.server.HttpChannel - /api/gtfs-rt-feed/2/feedMessage
javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsRtFeed.getFeedMessage(GtfsRtFeed.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	... 17 more
[qtp7548983-21] WARN org.eclipse.jetty.server.HttpChannel - Could not send response error 500: javax.servlet.ServletException: java.lang.NullPointerException
[qtp7548983-22] WARN org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: java.lang.NullPointerException
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsRtFeed.getFeedMessage(GtfsRtFeed.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	... 17 more
~~~

I'm starting with a clean database (i.e., delete the local database files and let Hibernate recreate them) with the following:
* HART GTFS-rt - http://api.tampa.onebusaway.org:8088/vehicle-positions
* HART GTFS - http://gohart.org/google/google_transit.zip
* Default interval of 10 seconds

I just tested again, and it seems like Iteration 1 and 3 works and shows the plain text version of the feed, but Iteration 2 throws the above exception.

**Comment by mohangandhiGH** [comment]
@barbeau Ahhhh, I'm really sorry Sean for the wrong update in this Github [commit](https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/135/commits/4cd3d7f1dc10f94d4c9ea01693a438f76a7f5fbb). Thanks a lot for taking your time to test. 
I updated the changes in this latest [commit](https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/135/commits/9c078bc6458c01627661ed5849ecf15dbaff14cd).

**Comment by barbeau** [comment]
Thanks @mohangandhiGH, that looks much better!  I'll squash and merge now - will be great to have this in the master branch :).
